"""
Board Room Report Export: PDF and PPTX generation.
Uses fpdf2 for PDF and python-pptx for PowerPoint.
Produces professional multi-page documents from the structured report JSON.
"""
from __future__ import annotations

import io
import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ── Colour palette ────────────────────────────────────────────────────────────
_CYAN = (34, 211, 238)       # EchoMind brand primary
_NAVY = (5, 7, 10)           # dark bg
_DARK = (15, 23, 42)         # surface
_WHITE = (255, 255, 255)
_LIGHT_GREY = (241, 245, 249)
_MUTED = (100, 116, 139)
_VIOLET = (139, 92, 246)


# ── PDF Export ────────────────────────────────────────────────────────────────

def _safe_str(s: Any) -> str:
    if s is None:
        return ""
    return str(s).replace("\u2022", "-").replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"')


def generate_pdf(report: Dict[str, Any], session: Dict[str, Any]) -> bytes:
    """Generate a professional PDF report. Returns raw bytes."""
    import time as _time
    _t0 = _time.monotonic()
    try:
        from fpdf import FPDF
    except ImportError:
        raise RuntimeError("fpdf2 is required for PDF export. Run: pip install fpdf2")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(left=20, top=20, right=20)

    def _add_cover_page():
        pdf.add_page()
        # Header bar
        pdf.set_fill_color(*_DARK)
        pdf.rect(0, 0, 210, 60, "F")
        pdf.set_fill_color(*_CYAN)
        pdf.rect(0, 58, 210, 4, "F")

        # Logo/brand text
        pdf.set_xy(20, 15)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_CYAN)
        pdf.cell(0, 6, "ECHOMIND  |  Board Room Mode", ln=True)

        pdf.set_xy(20, 28)
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(*_WHITE)
        title = _safe_str(session.get("title", "Board Room Report"))
        pdf.cell(0, 12, title[:60], ln=True)

        # Meta info
        pdf.set_xy(20, 75)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_DARK)
        loc = _safe_str(session.get("location", ""))
        date_str = _safe_str(session.get("started_at", ""))
        if date_str:
            try:
                dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
                date_str = dt.strftime("%B %d, %Y  %H:%M")
            except Exception:
                pass
        dur = session.get("duration_sec")
        dur_str = ""
        if dur:
            minutes, secs = divmod(int(dur), 60)
            hours, minutes = divmod(minutes, 60)
            dur_str = f"{hours}h {minutes}m" if hours else f"{minutes}m {secs}s"

        for label, value in [("Location:", loc), ("Date:", date_str), ("Duration:", dur_str)]:
            if value:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(*_MUTED)
                pdf.cell(32, 7, label)
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(*_DARK)
                pdf.cell(0, 7, _safe_str(value)[:80], ln=True)

        # Participants
        participants = report.get("participants", [])
        if participants:
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_MUTED)
            pdf.cell(0, 7, "Participants:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*_DARK)
            for p in participants:
                name = _safe_str(p.get("name", "Unknown"))
                turns = p.get("speaking_turns", 0)
                pdf.cell(0, 6, f"  - {name}  ({turns} speaking turns)", ln=True)

        # Generated at footer
        pdf.set_xy(20, 265)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 5, f"Generated by EchoMind Board Room Mode  |  {report.get('generated_at', '')[:19]}", ln=True)

    def _section_header(title: str):
        pdf.ln(3)
        pdf.set_fill_color(*_DARK)
        pdf.set_text_color(*_CYAN)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, _safe_str(title), ln=True, fill=False)
        pdf.set_fill_color(*_CYAN)
        pdf.rect(pdf.get_x(), pdf.get_y(), 170, 1, "F")
        pdf.ln(4)

    def _body_text(text: str, max_chars: int = 3000):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        safe = _safe_str(text)[:max_chars]
        pdf.multi_cell(0, 6, safe)
        pdf.ln(2)

    def _bullet(text: str):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        safe = "  - " + _safe_str(text)[:200]
        pdf.multi_cell(0, 6, safe)

    def _add_section_page():
        pdf.add_page()
        pdf.set_xy(20, 20)

    _add_cover_page()

    # Executive Summary
    _add_section_page()
    _section_header("Executive Summary")
    _body_text(report.get("executive_summary", "Not available."))

    # Key Discussion Points
    key_points = report.get("key_discussion_points", [])
    if key_points:
        _section_header("Key Discussion Points")
        for kp in key_points:
            topic = _safe_str(kp.get("topic", ""))
            if topic:
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(30, 30, 30)
                pdf.cell(0, 8, f"  {topic}", ln=True)
            summary = kp.get("summary", "")
            if summary:
                _body_text(summary, max_chars=600)
            rag_ev = kp.get("rag_evidence", [])
            if rag_ev:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(*_MUTED)
                src = _safe_str(rag_ev[0].get("source", ""))
                snippet = _safe_str(rag_ev[0].get("text", ""))[:120]
                pdf.multi_cell(0, 5, f"    [Evidence: {src}] {snippet}...")
                pdf.ln(1)
            pdf.ln(2)

    # Decisions
    decisions = report.get("decisions", [])
    if decisions:
        if pdf.get_y() > 220:
            _add_section_page()
        _section_header("Decisions Made")
        for d in decisions:
            _bullet(d)
        pdf.ln(3)

    # Action Items
    action_items = report.get("action_items", [])
    if action_items:
        if pdf.get_y() > 200:
            _add_section_page()
        _section_header("Action Items")
        # Table header
        pdf.set_fill_color(*_DARK)
        pdf.set_text_color(*_WHITE)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(90, 7, "Action Item", border=0, fill=True)
        pdf.cell(50, 7, "Owner", border=0, fill=True)
        pdf.cell(30, 7, "Priority", border=0, fill=True, ln=True)
        pdf.set_fill_color(248, 250, 252)
        for i, item in enumerate(action_items):
            pdf.set_text_color(30, 30, 30)
            pdf.set_font("Helvetica", "", 9)
            fill = i % 2 == 0
            act = _safe_str(item.get("item", ""))[:80]
            own = _safe_str(item.get("owner", "Unknown"))[:30]
            pri = _safe_str(item.get("priority", "Medium"))
            pdf.cell(90, 6, act, border=0, fill=fill)
            pdf.cell(50, 6, own, border=0, fill=fill)
            pdf.cell(30, 6, pri, border=0, fill=fill, ln=True)
        pdf.ln(4)

    # RAG Evidence
    rag_evidence = report.get("rag_evidence", [])
    if rag_evidence:
        if pdf.get_y() > 200:
            _add_section_page()
        _section_header("Supporting Evidence from Knowledge Base")
        for ev in rag_evidence[:6]:
            src = _safe_str(ev.get("source", ""))
            sec = _safe_str(ev.get("section", ""))
            txt = _safe_str(ev.get("text", ""))[:300]
            score = ev.get("score", 0)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_VIOLET)
            pdf.cell(0, 6, f"[{src}]  {sec}  (relevance: {score:.2f})", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 5, txt)
            pdf.ln(3)

    # Contradictions
    contradictions = report.get("contradictions", [])
    if contradictions:
        if pdf.get_y() > 220:
            _add_section_page()
        _section_header("Contradictions & Gaps Identified")
        for c in contradictions:
            _bullet(c)
        pdf.ln(3)

    # Recommendations
    recommendations = report.get("recommendations", [])
    if recommendations:
        if pdf.get_y() > 220:
            _add_section_page()
        _section_header("Recommendations & Next Steps")
        for r in recommendations:
            _bullet(r)

    pdf_bytes = bytes(pdf.output())
    logger.info("boardroom.export.pdf.completed session_id=%s size_bytes=%d elapsed_sec=%.1f",
                session.get("id", "?"), len(pdf_bytes), _time.monotonic() - _t0)
    return pdf_bytes


# ── PPTX Export ──────────────────────────────────────────────────────────────

def generate_pptx(report: Dict[str, Any], session: Dict[str, Any]) -> bytes:
    """Generate a professional PPTX presentation. Returns raw bytes."""
    import time as _time
    _t0 = _time.monotonic()
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        raise RuntimeError("python-pptx is required for PPTX export.")

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    BRAND_CYAN = RGBColor(34, 211, 238)
    BRAND_DARK = RGBColor(5, 7, 10)
    BRAND_NAVY = RGBColor(15, 23, 42)
    BRAND_WHITE = RGBColor(255, 255, 255)
    BRAND_VIOLET = RGBColor(139, 92, 246)
    BRAND_MUTED = RGBColor(100, 116, 139)

    blank_layout = prs.slide_layouts[6]  # blank

    def _rgb(rgb: RGBColor):
        return rgb

    def _add_rect(slide, left, top, width, height, color: RGBColor):
        from pptx.util import Inches
        shape = slide.shapes.add_shape(1, left, top, width, height)  # MSO_SHAPE_TYPE.RECTANGLE
        shape.fill.solid()
        shape.fill.fore_color.rgb = color
        shape.line.fill.background()
        return shape

    def _add_text_box(slide, text: str, left, top, width, height,
                      font_size=18, bold=False, color: RGBColor = None,
                      italic=False, align=None):
        from pptx.util import Pt
        from pptx.enum.text import PP_ALIGN
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = _safe_str(text)[:500]
        run = p.runs[0] if p.runs else p.add_run()
        run.font.size = Pt(font_size)
        run.font.bold = bold
        run.font.italic = italic
        if color:
            run.font.color.rgb = color
        if align:
            p.alignment = align
        return txBox

    def _add_slide_bg(slide):
        """Dark background."""
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = BRAND_NAVY

    def _make_title_slide():
        slide = prs.slides.add_slide(blank_layout)
        _add_slide_bg(slide)
        # Left accent bar
        _add_rect(slide, Inches(0), Inches(0), Inches(0.08), Inches(7.5), BRAND_CYAN)
        # EchoMind label
        _add_text_box(slide, "ECHOMIND  |  BOARD ROOM MODE",
                      Inches(0.3), Inches(0.4), Inches(12), Inches(0.5),
                      font_size=11, bold=True, color=BRAND_CYAN)
        # Title
        title = _safe_str(session.get("title", "Board Room Report"))
        _add_text_box(slide, title[:60], Inches(0.3), Inches(1.2), Inches(12), Inches(1.5),
                      font_size=36, bold=True, color=BRAND_WHITE)
        # Subtitle line
        _add_rect(slide, Inches(0.3), Inches(2.8), Inches(5), Inches(0.04), BRAND_CYAN)
        # Meta
        date_str = _safe_str(session.get("started_at", ""))
        if date_str:
            try:
                dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
                date_str = dt.strftime("%B %d, %Y  %H:%M")
            except Exception:
                pass
        loc = _safe_str(session.get("location", ""))
        dur = session.get("duration_sec")
        dur_str = ""
        if dur:
            m, s = divmod(int(dur), 60)
            h, m = divmod(m, 60)
            dur_str = f"{h}h {m}m" if h else f"{m}m {s}s"
        meta_lines = [l for l in [date_str, loc, dur_str] if l]
        _add_text_box(slide, "  ".join(meta_lines), Inches(0.3), Inches(3.0), Inches(12), Inches(0.6),
                      font_size=13, color=BRAND_MUTED)
        # Participants
        participants = report.get("participants", [])
        if participants:
            plist = "  |  ".join(p.get("name", "?") for p in participants[:8])
            _add_text_box(slide, "Participants: " + plist, Inches(0.3), Inches(3.8), Inches(12), Inches(0.6),
                          font_size=11, color=BRAND_MUTED)
        # Generated at
        _add_text_box(slide, f"Generated: {report.get('generated_at', '')[:19]}",
                      Inches(0.3), Inches(6.8), Inches(12), Inches(0.4),
                      font_size=9, italic=True, color=BRAND_MUTED)

    def _make_content_slide(title: str, bullets: List[str], footnote: str = ""):
        slide = prs.slides.add_slide(blank_layout)
        _add_slide_bg(slide)
        # Header bar
        _add_rect(slide, Inches(0), Inches(0), Inches(13.33), Inches(1.1), BRAND_DARK)
        _add_rect(slide, Inches(0), Inches(1.0), Inches(13.33), Inches(0.06), BRAND_CYAN)
        _add_text_box(slide, title, Inches(0.4), Inches(0.15), Inches(12.5), Inches(0.8),
                      font_size=22, bold=True, color=BRAND_CYAN)

        # Build multi-bullet text frame
        from pptx.util import Pt, Inches
        from pptx.dml.color import RGBColor
        txBox = slide.shapes.add_textbox(Inches(0.4), Inches(1.2), Inches(12.5), Inches(5.8))
        tf = txBox.text_frame
        tf.word_wrap = True
        for i, bullet in enumerate(bullets[:20]):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            p.text = "-  " + _safe_str(bullet)[:200]
            run = p.runs[0] if p.runs else p.add_run()
            run.font.size = Pt(14)
            run.font.color.rgb = RGBColor(220, 230, 241)
            p.space_before = Pt(4)

        if footnote:
            _add_text_box(slide, footnote[:120], Inches(0.4), Inches(6.9), Inches(12.5), Inches(0.4),
                          font_size=9, italic=True, color=BRAND_MUTED)

    def _make_action_items_slide(items: List[Dict]):
        from pptx.util import Pt, Inches
        from pptx.dml.color import RGBColor
        slide = prs.slides.add_slide(blank_layout)
        _add_slide_bg(slide)
        _add_rect(slide, Inches(0), Inches(0), Inches(13.33), Inches(1.1), BRAND_DARK)
        _add_rect(slide, Inches(0), Inches(1.0), Inches(13.33), Inches(0.06), BRAND_CYAN)
        _add_text_box(slide, "Action Items", Inches(0.4), Inches(0.15), Inches(12.5), Inches(0.8),
                      font_size=22, bold=True, color=BRAND_CYAN)

        # Column headers
        y = Inches(1.25)
        for x, w, lbl in [(0.4, 6.5, "Action Item"), (7.0, 3.5, "Owner"), (10.6, 2.0, "Priority")]:
            tb = slide.shapes.add_textbox(Inches(x), y, Inches(w), Inches(0.35))
            tf = tb.text_frame
            p = tf.paragraphs[0]
            p.text = lbl
            run = p.runs[0] if p.runs else p.add_run()
            run.font.size = Pt(11)
            run.font.bold = True
            run.font.color.rgb = BRAND_MUTED

        y_pos = Inches(1.65)
        row_h = Inches(0.48)
        pri_colors = {"High": RGBColor(248, 113, 113), "Medium": RGBColor(251, 191, 36), "Low": RGBColor(74, 222, 128)}
        for i, item in enumerate(items[:10]):
            if y_pos > Inches(6.9):
                break
            fill = RGBColor(20, 28, 45) if i % 2 == 0 else BRAND_NAVY
            _add_rect(slide, Inches(0.3), y_pos, Inches(12.7), row_h, fill)
            act = _safe_str(item.get("item", ""))[:80]
            own = _safe_str(item.get("owner", "Unknown"))[:25]
            pri = _safe_str(item.get("priority", "Medium"))
            pri_col = pri_colors.get(pri, RGBColor(148, 163, 184))
            for x, w, txt, col in [
                (0.4, 6.5, act, RGBColor(220, 230, 241)),
                (7.0, 3.5, own, BRAND_MUTED),
                (10.6, 2.0, pri, pri_col),
            ]:
                tb = slide.shapes.add_textbox(Inches(x), y_pos + Inches(0.06), Inches(w), row_h - Inches(0.1))
                tf = tb.text_frame
                p = tf.paragraphs[0]
                p.text = txt
                run = p.runs[0] if p.runs else p.add_run()
                run.font.size = Pt(11)
                run.font.color.rgb = col
            y_pos += row_h

    def _make_rag_slide(chunks: List[Dict]):
        bullets = []
        for c in chunks[:6]:
            src = _safe_str(c.get("source", ""))
            txt = _safe_str(c.get("text", ""))[:120]
            bullets.append(f"[{src}]  {txt}...")
        _make_content_slide("Supporting Evidence from Knowledge Base", bullets)

    # Build slides
    _make_title_slide()

    # Executive Summary
    summary = report.get("executive_summary", "")
    if summary:
        _make_content_slide("Executive Summary", [summary[:800]])

    # Key Discussion Points
    key_points = report.get("key_discussion_points", [])
    for kp in key_points:
        topic = kp.get("topic", "")
        summary_text = kp.get("summary", "")
        bullets = [ln.strip().lstrip("•- ") for ln in summary_text.split("\n") if ln.strip()]
        if not bullets:
            bullets = [summary_text[:200]] if summary_text else []
        _make_content_slide(f"Topic: {topic}", bullets[:8])

    # Decisions
    decisions = report.get("decisions", [])
    if decisions:
        _make_content_slide("Decisions Made", decisions[:12])

    # Action Items
    action_items = report.get("action_items", [])
    if action_items:
        _make_action_items_slide(action_items)

    # RAG Evidence
    rag_evidence = report.get("rag_evidence", [])
    if rag_evidence:
        _make_rag_slide(rag_evidence)

    # Contradictions
    contradictions = report.get("contradictions", [])
    if contradictions:
        _make_content_slide("Contradictions & Gaps", contradictions[:10])

    # Recommendations
    recommendations = report.get("recommendations", [])
    if recommendations:
        _make_content_slide("Recommendations & Next Steps", recommendations[:8])

    # Closing slide
    slide = prs.slides.add_slide(blank_layout)
    _add_slide_bg(slide)
    _add_rect(slide, Inches(0), Inches(0), Inches(13.33), Inches(7.5), BRAND_DARK)
    _add_rect(slide, Inches(4), Inches(3.5), Inches(5.33), Inches(0.06), BRAND_CYAN)
    _add_text_box(slide, "EchoMind Board Room Mode", Inches(0), Inches(2.5), Inches(13.33), Inches(0.8),
                  font_size=28, bold=True, color=BRAND_CYAN)
    _add_text_box(slide, "Powered by NVIDIA TensorRT-LLM + Parakeet Multitalker ASR + RAG",
                  Inches(0), Inches(3.8), Inches(13.33), Inches(0.6),
                  font_size=13, italic=True, color=BRAND_MUTED)

    buf = io.BytesIO()
    prs.save(buf)
    pptx_bytes = buf.getvalue()
    logger.info("boardroom.export.pptx.completed session_id=%s size_bytes=%d elapsed_sec=%.1f",
                session.get("id", "?"), len(pptx_bytes), _time.monotonic() - _t0)
    return pptx_bytes
